on: [push, pull_request]
name: CI/CD
jobs:
  build:
    name: "Build on ${{ matrix.os }}, ${{ matrix.version }} (${{ matrix.variant }})"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        variant: ["CS", "BC"]
        version: ["7.8", "current"]
        os: ["macos-latest", "ubuntu-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.9
      with:
        architecture: x64
        distribution: full
        variant: ${{ matrix.variant }}
        version: ${{ matrix.version }}

    - name: Install pkg and deps
      run: raco pkg install --batch --auto sass/

    - name: Run tests
      run: raco test -j 4 -l sass
